
services:
  database:
    image: mysql:8.0
    container_name: blog_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_system
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/bd_dump.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - blog-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend
    restart: always
    environment:
      PORT: 4000
      NODE_ENV: production
      CLIENT_URL: http://localhost:3000
      JWT_SECRET: super_secret_jwt_key_mindgroup_2026
      JWT_EXPIRES_IN: 7d
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: blog_system
      DB_PORT: 3306
    ports:
      - '4000:4000'
    depends_on:
      database:
        condition: service_healthy
    networks:
      - blog-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:4000/api
    container_name: blog_frontend
    restart: always
    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - blog-network

volumes:
  mysql_data:

networks:
  blog-network:
    driver: bridge
